---
title: "How to generate data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to generate data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Importing the package
```{r setup}
library(clusterwiselmm)
library(ggplot2)
```
## Defining the random effets correlation matrices
```{r}
lvl2_corr_mat = matrix(c(1, 0,
                          0, 1), 2, 2)
lvl3_corr_mat = matrix(c(10, 0,
                          0, 10), 2, 2)
```
## Generate 3 levels data with 3 groups that contains each 10 subgroups, and each subgroup contains 30 individuals
```{r}
set.seed(100)
data = simulate_data( n1 = 30,
                      n2 = 10,
                      n3 = 3,
                      fixed_slope = -2,
                      fixed_intercept = 2,
                      lvl2_corr_mat = lvl2_corr_mat,
                      lvl3_corr_mat = lvl3_corr_mat,
                      sigma2 = 1
                      )
head(data, 5)
```
## Random effets coefficients
```{r}
print(c("random effet lvl3 intercepts ", unique(data$lvl3_intercepts)))
print(c("random effet lvl3 slopes ", unique(data$lvl3_slopes)))
print(c("random effet lvl2 intercepts ", unique(data$lvl2_intercepts)))
print(c("random effet lvl2 slopes ", unique(data$lvl2_slopes)))
```
## Visualise level 3 groups
```{r}
ggplot2::ggplot(data = data) + geom_point(aes(x = x, y= y, col=as.factor(lvl3))) + ggtitle("level 3 groupes")
```

